
#
# Directions
# 
DIR_NONE = 0
DIR_RIGHT = 1
DIR_LEFT = 2
#
# Section states
#
SECTION_EMPTY = 0
SECTION_BLOCKED = 1
SECTION_BOOKED = 2
SECTION_CLEAR = 3
SECTION_OCCUPIED = 4
SECTION_STOPPING = 5
SECTION_CONTINUING = 6
SECTION_STARTING = 7
SECTION_STOPPED = 8
SECTION_LEAVING = 9
SECTION_TERMINATING = 10
SECTION_TERMINATED = 11
SECTION_BASE_LAST = 12

